### ISSUE TITLE
beginner's guide

### ISSUE THREAD

**Issue by mmarub** [b-pub/dwin-ico-tools#1]
Hi. I wish to change my UI display for my 3d printer, but i dont understand how use your programm. Can you help me?

**Comment by patofoto** [comment]
I agree that a simple quick guide for non-coders would be great.

**Comment by hayhay7789** [comment]
Second this

**Comment by Mineplayerminer** [comment]
> I second this. I don't know it well enough to write a guide but I managed to use this successfully to change my UI. If you're still looking for some guidance I can do my best to provide. :)

How do you use it? I still cant figure out how to split that file.

**Comment by E-Studios** [comment]
Yeah we need some more info... just dragging the *.ICO file on the splitIco.py doesnt work.
sharing a youtube video or whatsoever is always welcome.

**Comment by Mineplayerminer** [comment]
> Yeah we need some more info... just dragging the *.ICO file on the splitIco.py doesnt work.
> sharing a youtube video or whatsoever is always welcome.

I found a way how to do it. I will try to make a video this afternoon.

**Comment by E-Studios** [comment]
> > Yeah we need some more info... just dragging the *.ICO file on the splitIco.py doesnt work.
> > sharing a youtube video or whatsoever is always welcome.
> 
> I found a way how to do it. I will try to make a video this afternoon.

Nice, let us know or if video istn possible maybe some step bty step written tutorial.

**Comment by Mineplayerminer** [comment]
> > > Yeah we need some more info... just dragging the *.ICO file on the splitIco.py doesnt work.
> > > sharing a youtube video or whatsoever is always welcome.
> > 
> > 
> > I found a way how to do it. I will try to make a video this afternoon.
> 
> Nice, let us know or if video istn possible maybe some step bty step written tutorial.

In short:

Extracting 9.ICO, python/or the directory and .exe of "python splitIco.py 9.ICO output"

Reverse: python makeIco.py output 9.ico

("output" is the name of the folder)

You also need a pillow library: python -m pip install pillow

**Comment by b-pub** [comment]
Hi folks, sorry to leave you hanging on getting this going. I hacked these script together quick and didn't really explain how to use them. I'm putting together the information into the toplevel README.md file which I'll commit soon.

**Comment by b-pub** [comment]
OK, I updated the project's README.md file. Check out the new "Usage" section.
