### ISSUE TITLE
DACAI boards use .zico instead of .ico

### ISSUE THREAD

**Issue by 42willow** [b-pub/dwin-ico-tools#6]
When I try and use this tool (after renaming the .zico file to .ico because it says it's incompatible) the extracted images are all corrupted (unreadable by windows photos anyway...)

I am trying to get the stock icon set back on a DACAI LCD screen on an Ender 3 V2 with new Marlin firmware...

**Comment by b-pub** [comment]
Unfortunately .zico sounds like a different file format that is incompatible with these scripts. I'm not familiar with that screen or its formats, so I'm afraid I can't help with this.

**Comment by 42willow** [comment]
Ok thank you
